version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/tap_aggregator"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/tap_core"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/tap_integration_tests"
    schedule:
      interval: "daily"