[package]
name="tap_aggregator"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "tap_aggregator"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.70"
tokio = { version = "1.27.0", features = ["macros", "signal"] }
tap_core = { path = "../tap_core" }
ethereum-types = "0.14.1"
jsonrpsee = { version = "0.18.0", features = ["server", "macros"] }
k256 = { version = "0.13.1", features = ["ecdsa", "serde"] }
ethers-signers = "2.0.3"
coins-bip39 = { version = "0.8.6", default-features = false, features = ["english"] }
clap = { version = "4.2.4", features = ["derive", "env"] }

[dev-dependencies]
jsonrpsee = { version = "0.18.0", features = ["http-client", "jsonrpsee-core"] }
rand_core = "0.6.4"
rstest = "0.17.0"
