[package]
name = "tap_eip712_message"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
alloy.workspace = true
serde.workspace = true
thiserror.workspace = true


[dev-dependencies]
msg = { path = "../tap_graph", package = "tap_graph" }
