[package]
name = "tap_integration_tests"
version = "0.1.12"
edition.workspace = true
license.workspace = true
repository.workspace = true
autotests = false
description = "Integration tests for the Timeline Aggregation Protocol."
publish = false

[dependencies]
tap_aggregator = { path = "../tap_aggregator" }
tap_core = { path = "../tap_core", version = "2.0.0" }
rand.workspace = true
anyhow.workspace = true
tokio.workspace = true
alloy.workspace = true
jsonrpsee = { workspace = true, features = ["jsonrpsee-http-client"] }
jsonrpsee-core = "0.24.7"


[dev-dependencies]
rstest.workspace = true
alloy = { workspace = true, features = ["signer-mnemonic"] }

[[test]]
name = "integration_tests"
path = "tests/lib.rs"
