[package]
name = "tap_receipt"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
alloy.workspace = true
anyhow.workspace = true
anymap3 = "1.0.1"
thiserror.workspace = true
serde.workspace = true
async-trait = "0.1.85"
tap_eip712_message = { path = "../tap_eip712_message" }

[dev-dependencies]
tokio.workspace = true
